---
# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure rabbitmq is started and enabled (if configured).
  service:
    name: "rabbitmq-server"
    state: "started"
    enabled: "yes"

- name: "Add User {{rabbitmq_username}}"
  shell: "{{item}}"
  with_items:
   - "rabbitmqctl add_user {{rabbitmq_username}} {{rabbitmq_password}}"
   - "rabbitmqctl set_user_tags {{rabbitmq_username}}  administrator"
   - "rabbitmqctl set_permissions -p / {{rabbitmq_username}} '.*' '.*' '.*'"

- name: Enable Web
  shell: rabbitmq-plugins enable rabbitmq_management mochiweb rabbitmq_web_dispatch
  when: "{{rabbitmq_webenable == 't' }}"

- name: Restart Rabbitmq
  service: name=rabbitmq-server state=restarted enabled=yes
